language: python
python:
  - '3.7.5'

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "pytest -p no:warnings --cov=."
  - docker-compose run app sh -c "flake8 ."
  - docker-compose run app sh -c "black --exclude=migrations ."
  - docker-compose run app sh -c "isort ./*/*.py --check-only"
