# Generated by Django 3.0.5 on 2020-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
