# Generated by Django 3.0.5 on 2020-05-04 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateField()),
                ('renewal_cycle_days', models.IntegerField(choices=[('30', 'Every 30 days'), ('60', 'Every 60 days'), ('90', 'Every 90 days'), ('120', 'Every 120 days'), ('150', 'Every 150 days'), ('180', 'Every 180 days')])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
