# Generated by Django 3.0.5 on 2020-05-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='renewal_cycle_days',
            field=models.IntegerField(choices=[(30, 'Every 30 days'), (60, 'Every 60 days'), (90, 'Every 90 days'), (120, 'Every 120 days'), (150, 'Every 150 days'), (180, 'Every 180 days')]),
        ),
    ]
